version: '3'
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    privileged: true
    ports:
      - "27017:27017"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./mongodata:/data/db
