version: '3'
services:
  elasticsearch: # Elasticsearch Instance
    privileged: true
    container_name: es
    image: elasticsearch:6.4.2
    volumes: # Persist ES data in seperate "esdata" volume
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"