version: "2"
services:
  mydb:
    build: ./mysql
    container_name: "mydb"
    privileged: true

    ports:
      - "3306:3306"
    volumes:
      - /server/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  myredis:
    build: ./redis
    container_name: "myredis"
    privileged: true
    
    ports:
      - "6379:6379"
    volumes:
      - /server/redis:/data
  myphp:
    build: ./php
    container_name: "myphp"
    privileged: true
    ports:
      - "9000:9000"
    volumes:
      - /server/www:/var/www/html
      - /server/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - "mydb"
      - "myredis"
  mynginx:
    build: ./nginx
    container_name: "mynginx"
    privileged: true
    ports:
      - "80:80"
    links:
      - "myphp"
    volumes:
      - /server/www:/usr/share/nginx/html
      - /server/nginx:/etc/nginx
      - /server/logs/nginx.logs:/var/log/nginx
