version: "2"
services:
  mydb:
    build: ./mysql
    container_name: "mydb"
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command: "--character-set-server=utf8"
  myredis:
    build: ./redis
    container_name: "myredis"
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - ../redis/data:/data
      - ../redis/redis.conf:/etc/redis/redis.conf
  myphp:
    build: ./php
    container_name: "myphp"
    privileged: true
    ports:
      - "9000:9000"
    volumes:
      - ../www:/var/www/html
      - ../php/php.ini:/usr/local/etc/php/php.ini
    links:
      - "mydb"
      - "myredis"
  mynginx:
    build: ./nginx
    container_name: "mynginx"
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    links:
      - "myphp"
    volumes:
      - ../www:/usr/share/nginx/html
      - ../nginx:/etc/nginx
      - ../logs/nginx:/var/log/nginx
