version: "2"
services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
  mysql:
    image: "mysql:latest"
    container_name: "mysql"
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/cnf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456